### PR TITLE
Split br_if and br/return to avoid one more branch

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by axic** [comment]
@chfast could you run benchmarking on this?

**Comment by chfast** [comment]
```
fizzy/execute/blake2b/512_bytes_rounds_1_mean                     +0.0859         +0.0860            73            79            73            79
fizzy/execute/blake2b/512_bytes_rounds_16_mean                    +0.0801         +0.0802          1091          1178          1091          1178
fizzy/execute/ecpairing/onepoint_mean                             +0.0551         +0.0551        424579        447964        424583        447968
fizzy/execute/keccak256/512_bytes_rounds_1_mean                   +0.0160         +0.0160            88            89            88            89
fizzy/execute/keccak256/512_bytes_rounds_16_mean                  +0.0120         +0.0120          1269          1284          1269          1284
fizzy/execute/memset/256_bytes_mean                               +0.0773         +0.0776             6             7             6             7
fizzy/execute/memset/60000_bytes_mean                             +0.0922         +0.0922          1291          1410          1291          1410
fizzy/execute/mul256_opt0/input0_mean                             +0.0270         +0.0273            24            24            24            24
fizzy/execute/mul256_opt0/input1_mean                             +0.0264         +0.0265            24            24            24            24
fizzy/execute/sha1/512_bytes_rounds_1_mean                        +0.1059         +0.1060            77            86            77            86
fizzy/execute/sha1/512_bytes_rounds_16_mean                       +0.1131         +0.1131          1065          1186          1065          1186
fizzy/execute/sha256/512_bytes_rounds_1_mean                      +0.0885         +0.0885            75            81            75            81
fizzy/execute/sha256/512_bytes_rounds_16_mean                     +0.0918         +0.0918          1014          1107          1014          1107
fizzy/execute/micro/factorial/10_mean                             +0.0160         +0.0163             1             1             1             1
fizzy/execute/micro/factorial/20_mean                             +0.0138         +0.0148             2             2             2             2
fizzy/execute/micro/fibonacci/24_mean                             +0.0194         +0.0194         11269         11488         11270         11488
fizzy/execute/micro/host_adler32/1_mean                           -0.0150         -0.0134             1             1             1             1
fizzy/execute/micro/host_adler32/100_mean                         +0.0265         +0.0263             6             6             6             6
fizzy/execute/micro/host_adler32/1000_mean                        +0.0287         +0.0286            58            60            58            60
fizzy/execute/micro/spinner/1_mean                                -0.0145         -0.0138             0             0             0             0
fizzy/execute/micro/spinner/1000_mean                             +0.1650         +0.1653             8             9             8             9
```

**Comment by axic** [comment]
@chfast I wonder whether that is due to the noexcept (that commit gave me similar increase), can you remove that commit?

**Comment by chfast** [comment]
After removing the commit, it gets worse.
```
fizzy/execute/blake2b/512_bytes_rounds_1_mean                     +0.0944         +0.0945            73            79            73            79
fizzy/execute/blake2b/512_bytes_rounds_16_mean                    +0.0811         +0.0811          1091          1179          1091          1179
fizzy/execute/ecpairing/onepoint_mean                             +0.0704         +0.0704        424579        454484        424583        454487
fizzy/execute/keccak256/512_bytes_rounds_1_mean                   +0.0128         +0.0128            88            89            88            89
fizzy/execute/keccak256/512_bytes_rounds_16_mean                  +0.0137         +0.0137          1269          1286          1269          1286
fizzy/execute/memset/256_bytes_mean                               +0.0776         +0.0780             6             7             6             7
fizzy/execute/memset/60000_bytes_mean                             +0.0924         +0.0924          1291          1410          1291          1410
fizzy/execute/mul256_opt0/input0_mean                             +0.0195         +0.0197            24            24            24            24
fizzy/execute/mul256_opt0/input1_mean                             +0.0220         +0.0222            24            24            24            24
fizzy/execute/sha1/512_bytes_rounds_1_mean                        +0.1050         +0.1051            77            86            77            86
fizzy/execute/sha1/512_bytes_rounds_16_mean                       +0.1136         +0.1136          1065          1186          1065          1186
fizzy/execute/sha256/512_bytes_rounds_1_mean                      +0.0887         +0.0888            75            81            75            81
fizzy/execute/sha256/512_bytes_rounds_16_mean                     +0.0931         +0.0931          1014          1108          1014          1109
fizzy/execute/micro/factorial/10_mean                             +0.0114         +0.0111             1             1             1             1
fizzy/execute/micro/factorial/20_mean                             +0.0141         +0.0144             2             2             2             2
fizzy/execute/micro/fibonacci/24_mean                             +0.0318         +0.0318         11269         11628         11270         11628
fizzy/execute/micro/host_adler32/1_mean                           +0.0020         +0.0032             1             1             1             1
fizzy/execute/micro/host_adler32/100_mean                         -0.0015         -0.0016             6             6             6             6
fizzy/execute/micro/host_adler32/1000_mean                        +0.0021         +0.0021            58            58            58            59
fizzy/execute/micro/spinner/1_mean                                -0.0159         -0.0153             0             0             0             0
fizzy/execute/micro/spinner/1000_mean                             +0.1643         +0.1646             8             9             8             9
```

**Comment by chfast** [comment]
If you see the old code, it can be reordered to 
```cpp
        case Instr::br_if:
            if (static_cast<uint32_t>(stack.pop()) == 0)
            {
                immediates += BranchImmediateSize;
                break;
            }
            [[fallthrough]];
        case Instr::br:
        case Instr::return_:
            branch(code, stack, pc, immediates);
            break;
```
And maybe compiler is doing that anyway.

**Comment by axic** [comment]
> If you see the old code, it can be reordered to

Would it make sense making it explicit?

**Comment by chfast** [comment]
> > If you see the old code, it can be reordered to
> 
> Would it make sense making it explicit?

Sure.

**Comment by chfast** [comment]
Are you going to finish this?

**Comment by axic** [comment]
Finish as in?

1. Should I keep the "noexcept"?

 2. Should I commit the version with `[fallthrough]` as that seems to be what the compiler is doing and it doesn't cause any regression?

**Comment by axic** [comment]
Rebased this and added 3 options in total. Maybe one of them does not cause any regression. If not we can close this.

**Comment by axic** [comment]
@chfast do you want to benchmark this again? If there's no good outcome, we should close it.

**Comment by chfast** [comment]
All of the versions introduce similar performance regression, but also drastically change code layout (can be the reason of the regression).

```
fizzy/execute/blake2b/512_bytes_rounds_1_mean                     +0.0702         +0.0702            83            88            83            88                                                                                 
fizzy/execute/blake2b/512_bytes_rounds_16_mean                    +0.0706         +0.0706          1252          1340          1252          1340                                                                                 
fizzy/execute/ecpairing/onepoint_mean                             +0.0778         +0.0778        390213        420580        390216        420585                                                                                 
fizzy/execute/keccak256/512_bytes_rounds_1_mean                   +0.0718         +0.0717            97           104            97           104                                                                                 
fizzy/execute/keccak256/512_bytes_rounds_16_mean                  +0.0684         +0.0684          1427          1525          1427          1525                                                                                 
fizzy/execute/memset/256_bytes_mean                               +0.1660         +0.1660             6             7             6             7                                                                                 
fizzy/execute/memset/60000_bytes_mean                             +0.1806         +0.1806          1395          1647          1395          1647                                                                                 
fizzy/execute/mul256_opt0/input1_mean                             +0.1349         +0.1349            26            29            26            29                                                                                 
fizzy/execute/ramanujan_pi/33_runs_mean                           +0.1017         +0.1017           115           127           115           127                                                                                 
fizzy/execute/sha1/512_bytes_rounds_1_mean                        +0.1557         +0.1557            83            96            83            96                                                                                 
fizzy/execute/sha1/512_bytes_rounds_16_mean                       +0.1645         +0.1645          1153          1343          1153          1343                                                                                 
fizzy/execute/sha256/512_bytes_rounds_1_mean                      +0.1510         +0.1511            81            93            81            93                                                                                 
fizzy/execute/sha256/512_bytes_rounds_16_mean                     +0.1553         +0.1553          1119          1293          1119          1293                                                                                 
fizzy/execute/taylor_pi/pi_1000000_runs_mean                      +0.0402         +0.0402         40051         41660         40052         41660                                                                                 
fizzy/execute/micro/eli_interpreter/exec105_mean                  +0.1258         +0.1258             4             5             4             5
fizzy/execute/micro/factorial/20_mean                             +0.0345         +0.0345             1             1             1             1
fizzy/execute/micro/fibonacci/24_mean                             +0.0506         +0.0506          4889          5136          4889          5136
fizzy/execute/micro/host_adler32/1_mean                           +0.0277         +0.0277             0             0             0             0
fizzy/execute/micro/host_adler32/1000_mean                        +0.0612         +0.0612            29            31            29            31
fizzy/execute/micro/spinner/1_mean                                +0.0523         +0.0523             0             0             0             0
fizzy/execute/micro/spinner/1000_mean                             +0.0818         +0.0818             9            10             9            10
```

**Comment by axic** [comment]
@chfast wondering if anything has changed since regarding this. We should have some umbrella issue collecting these optimisation ideas/tests so we can revisit them.

**Comment by chfast** [comment]
Yes, we can collect these somehow. About this particular case, I think we are too slow to measure any difference.

**Pull request closed without merging**
