### PR TITLE
Rename execution_result -> ExecutionResult

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by axic** [comment]
Nice, I was about to ask why not rename it.

**Comment by chfast** [comment]
Move it to separate header? I will use it also in `WasmEngine`.

**Comment by axic** [comment]
> Move it to separate header? I will use it also in WasmEngine.

I think that is a bad idea -- we would be trying to apply Fizzy's API to other engines. Why can't we leave WasmEngine as is, already uses optional?

Probably I could / will change my mind if we would expose host functions in WasmEngine.

**Comment by chfast** [comment]
> I think that is a bad idea -- we would be trying to apply Fizzy's API to other engines. Why can't we leave WasmEngine as is, already uses optional?

Sounds good.

**Pull request merged**
