### PR TITLE
Storage for locals

### PR DESCRIPTION
**Pull request by chfast**
Does not seem to make big difference, more benchmarks to be done soon...

### CODE REVIEW

**Comment by gumb0** [comment]
I tried to benchmark this (against PR base), here're the results, not much difference
```
Benchmark                                                            Time             CPU      Time Old      Time New       CPU Old       CPU New
-------------------------------------------------------------------------------------------------------------------------------------------------
fizzy/execute/blake2b/512_bytes_rounds_1_pvalue                    0.0002          0.0002      U Test, Repetitions: 10 vs 10
fizzy/execute/blake2b/512_bytes_rounds_1_mean                     -0.0157         -0.0156           189           186           189           187
fizzy/execute/blake2b/512_bytes_rounds_1_median                   -0.0132         -0.0131           189           186           189           186
fizzy/execute/blake2b/512_bytes_rounds_1_stddev                   -0.5872         -0.5854             2             1             2             1
fizzy/execute/blake2b/512_bytes_rounds_16_pvalue                   0.0036          0.0046      U Test, Repetitions: 10 vs 10
fizzy/execute/blake2b/512_bytes_rounds_16_mean                    -0.0064         -0.0063          2834          2816          2833          2815
fizzy/execute/blake2b/512_bytes_rounds_16_median                  -0.0056         -0.0055          2829          2813          2828          2813
fizzy/execute/blake2b/512_bytes_rounds_16_stddev                  +0.5525         +0.5487            10            16            10            16
fizzy/execute/ecpairing/onepoint_pvalue                            0.0002          0.0002      U Test, Repetitions: 10 vs 10
fizzy/execute/ecpairing/onepoint_mean                             -0.0660         -0.0661       1117536       1043761       1117455       1043634
fizzy/execute/ecpairing/onepoint_median                           -0.0634         -0.0635       1114297       1043633       1114265       1043548
fizzy/execute/ecpairing/onepoint_stddev                           -0.6124         -0.6142          6032          2338          6020          2323
fizzy/execute/keccak256/512_bytes_rounds_1_pvalue                  0.0002          0.0002      U Test, Repetitions: 10 vs 10
fizzy/execute/keccak256/512_bytes_rounds_1_mean                   +0.0536         +0.0534           211           222           211           222
fizzy/execute/keccak256/512_bytes_rounds_1_median                 +0.0502         +0.0500           211           222           211           222
fizzy/execute/keccak256/512_bytes_rounds_1_stddev                 +0.7042         +0.6736             1             2             1             2
fizzy/execute/keccak256/512_bytes_rounds_16_pvalue                 0.0002          0.0002      U Test, Repetitions: 10 vs 10
fizzy/execute/keccak256/512_bytes_rounds_16_mean                  +0.0782         +0.0782          3031          3268          3031          3267
fizzy/execute/keccak256/512_bytes_rounds_16_median                +0.0745         +0.0745          3038          3265          3038          3265
fizzy/execute/keccak256/512_bytes_rounds_16_stddev                +0.8777         +0.8677            26            49            26            49
fizzy/execute/memset/256_bytes_pvalue                              0.0002          0.0002      U Test, Repetitions: 10 vs 10
fizzy/execute/memset/256_bytes_mean                               -0.0174         -0.0176            17            16            17            16
fizzy/execute/memset/256_bytes_median                             -0.0198         -0.0204            17            16            17            16
fizzy/execute/memset/256_bytes_stddev                             +1.0421         +0.9718             0             0             0             0
fizzy/execute/memset/60000_bytes_pvalue                            0.0140          0.0140      U Test, Repetitions: 10 vs 10
fizzy/execute/memset/60000_bytes_mean                             -0.0110         -0.0110          3503          3464          3503          3464
fizzy/execute/memset/60000_bytes_median                           -0.0133         -0.0134          3500          3453          3499          3453
fizzy/execute/memset/60000_bytes_stddev                           +2.0086         +2.0234             9            26             9            26
fizzy/execute/mul256_opt0/input0_pvalue                            0.0002          0.0002      U Test, Repetitions: 10 vs 10
fizzy/execute/mul256_opt0/input0_mean                             -0.0916         -0.0919            65            59            65            59
fizzy/execute/mul256_opt0/input0_median                           -0.0927         -0.0927            65            59            65            59
fizzy/execute/mul256_opt0/input0_stddev                           -0.1719         -0.2832             0             0             0             0
fizzy/execute/mul256_opt0/input1_pvalue                            0.0002          0.0002      U Test, Repetitions: 10 vs 10
fizzy/execute/mul256_opt0/input1_mean                             -0.0887         -0.0887            65            59            65            59
fizzy/execute/mul256_opt0/input1_median                           -0.0877         -0.0878            65            59            65            59
fizzy/execute/mul256_opt0/input1_stddev                           -0.4546         -0.4514             0             0             0             0
fizzy/execute/sha1/512_bytes_rounds_1_pvalue                       0.0002          0.0002      U Test, Repetitions: 10 vs 10
fizzy/execute/sha1/512_bytes_rounds_1_mean                        -0.0107         -0.0104           194           192           194           192
fizzy/execute/sha1/512_bytes_rounds_1_median                      -0.0101         -0.0099           194           192           194           192
fizzy/execute/sha1/512_bytes_rounds_1_stddev                      +0.1994         +0.2311             0             0             0             0
fizzy/execute/sha1/512_bytes_rounds_16_pvalue                      0.0036          0.0058      U Test, Repetitions: 10 vs 10
fizzy/execute/sha1/512_bytes_rounds_16_mean                       -0.0038         -0.0036          2660          2650          2660          2650
fizzy/execute/sha1/512_bytes_rounds_16_median                     -0.0054         -0.0052          2661          2646          2660          2647
fizzy/execute/sha1/512_bytes_rounds_16_stddev                     +0.9248         +0.9149             7            14             7            14
fizzy/execute/sha256/512_bytes_rounds_1_pvalue                     0.0002          0.0002      U Test, Repetitions: 10 vs 10
fizzy/execute/sha256/512_bytes_rounds_1_mean                      -0.0806         -0.0804           197           181           197           181
fizzy/execute/sha256/512_bytes_rounds_1_median                    -0.0804         -0.0802           197           181           197           181
fizzy/execute/sha256/512_bytes_rounds_1_stddev                    -0.5585         -0.5576             0             0             0             0
fizzy/execute/sha256/512_bytes_rounds_16_pvalue                    0.0002          0.0002      U Test, Repetitions: 10 vs 10
fizzy/execute/sha256/512_bytes_rounds_16_mean                     -0.0851         -0.0850          2667          2440          2667          2440
fizzy/execute/sha256/512_bytes_rounds_16_median                   -0.0851         -0.0850          2668          2441          2667          2441
fizzy/execute/sha256/512_bytes_rounds_16_stddev                   -0.2784         -0.2762             4             3             4             3
fizzy/execute/micro/factorial/10_pvalue                            0.0002          0.0002      U Test, Repetitions: 10 vs 10
fizzy/execute/micro/factorial/10_mean                             +0.0175         +0.0178             3             3             3             3
fizzy/execute/micro/factorial/10_median                           +0.0194         +0.0199             3             3             3             3
fizzy/execute/micro/factorial/10_stddev                           -0.7293         -0.7382             0             0             0             0
fizzy/execute/micro/factorial/20_pvalue                            0.3847          0.1859      U Test, Repetitions: 10 vs 10
fizzy/execute/micro/factorial/20_mean                             +0.0001         +0.0008             5             5             5             5
fizzy/execute/micro/factorial/20_median                           +0.0009         +0.0016             5             5             5             5
fizzy/execute/micro/factorial/20_stddev                           -0.8678         -0.8655             0             0             0             0
fizzy/execute/micro/fibonacci/24_pvalue                            0.0002          0.0002      U Test, Repetitions: 10 vs 10
fizzy/execute/micro/fibonacci/24_mean                             +0.0101         +0.0104         35247         35604         35237         35604
fizzy/execute/micro/fibonacci/24_median                           +0.0093         +0.0095         35232         35558         35224         35558
fizzy/execute/micro/fibonacci/24_stddev                           -0.1711         -0.1403           104            86           100            86
fizzy/execute/micro/host_adler32/1_pvalue                          0.0002          0.0002      U Test, Repetitions: 10 vs 10
fizzy/execute/micro/host_adler32/1_mean                           -0.0695         -0.0691             1             1             1             1
fizzy/execute/micro/host_adler32/1_median                         -0.0711         -0.0707             1             1             1             1
fizzy/execute/micro/host_adler32/1_stddev                         -0.5073         -0.5047             0             0             0             0
fizzy/execute/micro/host_adler32/100_pvalue                        0.6232          0.6232      U Test, Repetitions: 10 vs 10
fizzy/execute/micro/host_adler32/100_mean                         -0.0017         -0.0017            15            15            15            15
fizzy/execute/micro/host_adler32/100_median                       -0.0028         -0.0028            15            15            15            15
fizzy/execute/micro/host_adler32/100_stddev                       -0.0183         -0.0193             0             0             0             0
fizzy/execute/micro/host_adler32/1000_pvalue                       0.9698          0.9698      U Test, Repetitions: 10 vs 10
fizzy/execute/micro/host_adler32/1000_mean                        -0.0014         -0.0014           149           148           149           148
fizzy/execute/micro/host_adler32/1000_median                      -0.0059         -0.0060           149           148           149           148
fizzy/execute/micro/host_adler32/1000_stddev                      -0.2565         -0.2571             2             1             2             1
fizzy/execute/micro/spinner/1_pvalue                               0.0002          0.0004      U Test, Repetitions: 10 vs 10
fizzy/execute/micro/spinner/1_mean                                +0.0086         +0.0084             1             1             1             1
fizzy/execute/micro/spinner/1_median                              +0.0090         +0.0089             1             1             1             1
fizzy/execute/micro/spinner/1_stddev                              -0.5344         -0.5380             0             0             0             0
fizzy/execute/micro/spinner/1000_pvalue                            0.0002          0.0002      U Test, Repetitions: 10 vs 10
fizzy/execute/micro/spinner/1000_mean                             +0.0281         +0.0275            24            24            24            24
fizzy/execute/micro/spinner/1000_median                           +0.0306         +0.0298            24            24            24            24
fizzy/execute/micro/spinner/1000_stddev                           -0.8765         -0.8854             0             0             0             0

```

**Comment by chfast** [comment]
I didn't have spectacular results either.

**Comment by axic** [comment]
What is the story with this?

**Comment by axic** [comment]
Wouldn't this be needed if we want to move `execute` to not have exceptions? I changed it to not `throw`, but `std::vector` could still imho.

**Comment by chfast** [comment]
Similar optimization done in #382.

**Pull request closed without merging**
